name: "Header Comments"
description: "GitHub Actions starter for TypeScript with automated releases"
author: "Koj <https://github.com/koj.co>"
inputs:
  directory:
    required: false
    description: "Directory to search for files in"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "umbrella"
  color: "purple"
