name: Test CI
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Test action
    runs-on: ubuntu-18.04
    if: "contains(github.event.head_commit.message, 'Deploy new version')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - uses: ./
        with:
          directory: src
      - name: Create PR with changes
        uses: peter-evans/create-pull-request@v3.9.1
